nodejs:
    environment:
        APPINSIGHTS_INSTRUMENTATIONKEY: "dummykey"
        CASE_MAINTENANCE_BASE_URL: "http://div-cms-aat.service.core-compute-aat.internal"
        DEPLOYMENT_ENV: "aat"
        EVIDENCE_MANAGEMENT_CLIENT_API_HEALTHCHECK_URL: "http://div-emca-aat.service.core-compute-aat.internal/health"
        EVIDENCE_MANAGEMENT_CLIENT_API_URL: "http://div-emca-aat.service.core-compute-aat.internal/"
        EVIDENCE_MANAGEMENT_CLIENT_API_UPLOAD_ENDPOINT: "/emclientapi/version/1/upload"
        EVIDENCE_MANAGEMENT_CLIENT_API_DOWNLOAD_ENDPOINT: "/emclientapi/version/1/download"
        FEES_AND_PAYMENTS_HEALTHCHECK_URL: "http://div-fps-aat.service.core-compute-aat.internal/health"
        FEES_AND_PAYMENTS_URL: "http://div-fps-aat.service.core-compute-aat.internal"
        IDAM_API_URL: "https://idam-api.aat.platform.hmcts.net"
        IDAM_APP_HEALHCHECK_URL: "https://idam-api.aat.platform.hmcts.net/health"
        IDAM_AUTHENTICATION_HEALHCHECK_URL: "https://idam-web-public.aat.platform.hmcts.net/health"
        IDAM_LOGIN_URL: "https://idam-web-public.aat.platform.hmcts.net/login"
        GOOGLE_ANALYTICS_ID: "TBD"
        ORCHESTRATION_SERVICE_AMEND_PETITION_URL: "http://div-cos-aat.service.core-compute-aat.internal/amend-petition"
        ORCHESTRATION_SERVICE_DRAFT_ENDPOINT: "http://div-cos-aat.service.core-compute-aat.internal/draftsapi/version/1"
        ORCHESTRATION_SERVICE_GET_PETITION_URL: "http://div-cos-aat.service.core-compute-aat.internal/retrieve-case"
        ORCHESTRATION_SERVICE_GET_AOS_PETITION_URL: "http://div-cos-aat.service.core-compute-aat.internal/retrieve-aos-case"
        ORCHESTRATION_SERVICE_POST_PETITION_URL: "http://div-cos-aat.service.core-compute-aat.internal/submit-da"
        ORCHESTRATION_SERVICE_HEALTH_URL: "http://div-cos-aat.service.core-compute-aat.internal/health"
        REDISCLOUD_URL: "redis://${SERVICE_NAME}-redis-master:6379"
        REFORM_ENVIRONMENT: "aat"
        PETITIONER_FRONTEND_URL: "https://div-pfe-aat.service.core-compute-aat.internal"
        DECREE_NISI_FRONTEND_URL: "https://div-dn-aat.service.core-compute-aat.internal"
        # TODO - this should be changed once we deploy AAT to AKS
        BASE_URL: "https://${SERVICE_NAME}.service.core-compute-preview.internal"
        PUBLIC_HOSTNAME: "https://${SERVICE_NAME}.service.core-compute-preview.internal"

    # Don't modify below here
    image: ${IMAGE_NAME}
    ingressHost: ${SERVICE_FQDN}